### ISSUE TITLE
uploadOptions / apostrophe in title attribute

### ISSUE THREAD

**Issue by lunanigra** [Pomax/node-flickrapi#70]
The following sample works quite file...
```
Flickr.authenticate(FlickrOptions, function(error, flickr) {
  var uploadOptions = {
    photos: [{
      title: "test",
      tags: [
        "happy fox",
        "test 1"
      ], ...
```
But if using "test'test" or "test\'test" as title the image upload does nothing. Means the title attribute contains an apostrophe character. No error and also now image uploaded to Flickr (photos uploaded []).
Can you reproduce this issue? Is there is simple fix or work-around?

**Comment by Pomax** [comment]
interesting, it might need HTML entities inside tags, which can totally be put in - I'll see if I can reproduce.

**Comment by Pomax** [comment]
fixed in v0.3.35

**Comment by lunanigra** [comment]
Thanks for fixing! How do I get the latest version? Then re-installing flickrapi the bower.json shows 0.3.34 and the behaviour is still the same...

**Comment by Pomax** [comment]
I'd say "don't use bower", install it with `npm` instead.

**Comment by lunanigra** [comment]
Ok, this is what I did. Just was looking for a way to verify that the right version is installed.

Unlickily it is still not working. A title like "test'test" stop the upload. So, I would like to do some more checks. Which file was changed?

**Comment by Pomax** [comment]
wow, it looks like I forgot to fix the title, only the tags. Let me reopen this and add the fix in for the rest of the fields too, what the heck.

**Comment by lunanigra** [comment]
Had you have a chance to fix already? Would be really cool :-)

**Comment by Pomax** [comment]
yeah, fixed in 0.3.36
